# Generated by Django 3.1.6 on 2021-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp2', '0011_writer_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='mpesa_code',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='comp',
            name='username',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
