# Generated by Django 3.2.6 on 2021-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp2', '0022_auto_20211005_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='inviter_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
